### ISSUE TITLE
Anyway to filter retweets?

### ISSUE THREAD

**Issue by mattgaidica** [ryangiglio/jquery-tweetMachine#15]
Seems like adding "+filter:retweet" has worked for others, but I don't see a clear way to add that. Without access to the timeline API, I don't see a good way to exclude replies. Thanks.

**Comment by ryangiglio** [comment]
When you say filter retweets, do you mean remove them from results or get them exclusively?

**Comment by mattgaidica** [comment]
Looks like someone made this into a separate issue, relates to getting results from the user timeline.
